# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f3bc6f2692836355761c5cf2d069cb6132f7de05c3779f7f2a667f9fa18fe42c2f8f15fdbd96dc90cc2f9a474eabda3dedbc8b2f277237eff39f55fce6721148

test:
  secret_key_base: 6760bf5d88cfaf26630b08273279e6ec08345c1f78b97e9d5b474b3509bd280af8d3bca3f1f95dc55fda8970954bced13e1022fed81d75f13b4e2bfc0d979a5c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
